# docker-compose.yml
version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your_jwt_secret_key
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - microservices-net

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/products
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PORT=3001
    depends_on:
      - mongodb
      - auth-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  mongodb_data: